name: Push to ECR public

on:
  push:
    branches: [ main ]

permissions:
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: ${{ secrets.REGISTRY_ALIAS }}
          REPOSITORY: ${{ secrets.AWS_REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }} 
        run: |
          IMAGE_URI=$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Image details
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: ${{ secrets.REGISTRY_ALIAS }}
          REPOSITORY: ${{ secrets.AWS_REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Pushed image: $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG"

